version: '3.1'

services:

  postgres_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'

  crud_fastapi_sqlalchemy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3333:3333'

  volumes:
    postgres_db: