"""first migrations

Revision ID: 974252c96baa
Revises: 
Create Date: 2022-11-14 21:26:41.767108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '974252c96baa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
